### ISSUE TITLE
oauth plugin issue: allowAPIKeyOnly/allowOAuthOnly breaks allowNoAuthorization

### ISSUE THREAD

**Issue by francesco38** [apigee/microgateway-plugins#63]
`AllowAPIKeyOnly` and `allowOAuthOnly` are configuration flags that should restrain where to look for authorization details in an incoming request, i.e. headers "x-api-key" (for a consumer key) or "authorization" for an Apigee OAuth token.
`allowNoAuthorization` and `allowInvalidautorization` are used to specify if oauth plugin should return a 401 when the authentication details are missing (for the first flag) or invalid (second flag), or let the request go.
I believe the first two flags (where to get authN details from) should not impact the behavior of the second set of flags (what to do with the authN details). However, setting one of the two flags from the first set to true breaks the behavior of allowNoAuthorization. De facto, no matter what is the value of allowNoAuthorization, it behaves as if it's set to "false".

**Comment by srinandan** [comment]
@francesco38 - i think those are contradictory statement in the yaml file and we shouldn't have to support it. on one hand, the user is saying `allowOAuthOnly` and then saying `allowNoAuthorization`. That doesn't make sense.

**Comment by francesco38** [comment]
@srinandan I'm sorry to disagree... But you have to consider that oauth plugin can perform authentication on either `Authorization` header or `x-api-key` header. 
To me, `allowOAuthOnly` (resp. `allowAPIKeyOnly`) means "please ignore anything in the header x-api-key" (resp. ignore Authorization header). 
Typically, in our implementation, `Authorization` is reversed for our internal OAuth2 authority (*not* Apigee Oauth), so we do no want apigee/oauth to use it. Therefore we set `allowAPIKeyOnly`. Still, we do not want apigee oauth authentication to be mandatory. So we set allowApiKeyOnly, allowNoAuthorization and this makes perfect sense!

**Comment by srinandan** [comment]
hmm...that is not how we envisioned `allowOAuthOnly` to be. The flag was meant to indicate OAuth header (Authorization) must be passed. 

Here is the docs link: https://docs.apigee.com/microgateway/content/edge-microgateway-release-notes-0 
`
allowOAuthOnly -- If set to true, every API must carry an Authorization header with a Bearer Access Token.
`
This is why I saw the two flags as contradictory. Let me restate the use case you're describing. The consumer may be passing an API Key and an OAuth token. But you only want to verify the OAuth token if it was sent. 

```
allowOAuthOnly: true
allowNoAuthorization: true
```
So this would translate to: 
1) Valid OAuth token and API Key was missing - allow it.
2) Valid OAuth token and invalid API Key - allow it (since we ignore API Keys)
3) Invalid OAuth token and valid API Key - reject it (since we validate OAuth tokens only)
4) Missing OAuth token and API Key (valid or invalid) - allow it (since OAuth is optional)
 
Is this what you want?

**Comment by francesco38** [comment]
@srinandan yes, this is what we want - except that we want `allowAPIKeyOnly: true` instead of `allowOAuthOnly` (as our `Authorization` header contains a different kind of bearer token).

```
allowAPIKeyOnly: true
allowNoAuthorization: true
```

which translates too:

- valid x-api-key: allow
- missing x-api-key: allow
- invalid x-api-key: deny

**Comment by asnowfix** [comment]
@srinandan let me revive that thread. You wrote:

> The consumer may be passing an API Key and an OAuth token. But you only want to verify the OAuth token if it was sent.
> So this would translate to:
>
> 1. Valid OAuth token and API Key was missing - allow it.
> 1. Valid OAuth token and invalid API Key - allow it (since we ignore API Keys)
> 1. Invalid OAuth token and valid API Key - reject it (since we validate OAuth tokens only)
> 1. Missing OAuth token and API Key (valid or invalid) - allow it (since OAuth is optional)
>
> Is this what you want?

Not exactly, what we want is: The consumer may be passing an API Key and an OAuth token. But we only want to verify the API Key, because the OAuth token comes from another (non-Apigee) OAuth authority. -> **We want to always ignore OAuth token & always demand a valid API key**.

So this would translate to:

1. Valid OAuth token and API Key was missing – reject it (we really want API key)
1. Valid OAuth token and invalid API Key - reject it (since we check API Keys first)
1. Invalid OAuth token and valid API Key - allow it (since we check API Keys first)
1. Missing OAuth token and valid API Key - allow it (since OAuth is optional)
1. Missing OAuth token and invalid API Key  - reject it it (we really want API key)

**Comment by victoranaylton** [comment]
@asnowfix @francesco38 @srinandan 

I've tested EMG 2.5.22-beta that comes with the apikeys plugin. This new plugin works properly in the scenarios above.
